[project]
name = 'Decentralized-Healthcare-Data-Management-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.patient-record]
path = 'contracts/patient-record.clar'
clarity_version = 2
epoch = 2.5

[contracts.prescription-management]
path = 'contracts/prescription-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.research-data-sharing]
path = 'contracts/research-data-sharing.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
